<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.dreamlike</groupId>
        <artifactId>VirtualThreadPlayground</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>VirtualThread-Scheduler-Io_uring</artifactId>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <netty.version>4.2.14.Final</netty.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-classes-io_uring</artifactId>
            <version>${netty.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-classes-epoll</artifactId>
            <version>${netty.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-classes-kqueue</artifactId>
            <version>${netty.version}</version>
            <scope>provided</scope>
        </dependency>


        <dependency>
            <groupId>io.github.dreamlike</groupId>
            <artifactId>VirtualThread-Scheduler-Core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.dreamlike</groupId>
            <artifactId>VirtualThread-Scheduler-Agent</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>